driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

driver_config:
  provision_command:
    - apt-get install net-tools

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[postgresql::server]
      - recipe[postgresql::client]
    attributes:
      postgresql:
        version: "9.6"
        users:
          - username: testuser
            password: s3kr1t
            login: true
        databases:
          - name: testdb
            owner: testuser
            template: template0
            encoding: utf8
            locale: en_US.utf8
            extensions:
              - adminpack
              - autoinc
              - btree_gin
              - btree_gist
              - chkpass
              - citext
              - cube
              - dict_int
              - dict_xsyn
              - earthdistance
              - file_fdw
              - fuzzystrmatch
              - hstore
              - insert_username
              - intagg
              - intarray
              - isn
              - lo
              - ltree
              - moddatetime
              - pageinspect
              - pg_buffercache
              - pg_freespacemap
              - pg_prewarm
              - pg_stat_statements
              - pg_trgm
              - pgcrypto
              - pgrowlocks
              - pgstattuple
              - postgres_fdw
              - refint
              - seg
              - sslinfo
              - tablefunc
              - tcn
              - timetravel
              - tsearch2
              - unaccent
              - xml2
        extensions:
          - name: dblink
            database: testdb
          - name: uuid-ossp
            database: testdb
