AllCops:
  Exclude:
    - ".bundle/**/*"
    - "vendor/**/*"

LineLength:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"  # Arrays use brackets

Style/SpaceBeforeFirstArg:
  Enabled: false  # too strict about metadata and certain formatting
